spring:
  cloud:
    stream:
      kafka:
        binder:
          brokers: localhost:9092
      bindings:
        organization-in:
          destination: organization
          contentType: application/json
        organization-out:
          destination: organization
          contentType: application/json